name: recipeapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Biotif-Bold.ttf
  #       - asset: assets/fonts/Biotif-Regular.ttf
  #         weight: 700
 
